User
lohoi/housecall pull request #5
Opened 2017-10-09 18:00 UTC by lohoi

2017-10-09 18:14 UTC, RemingtonReackhof requested changes
@lohoi remove the commented out code and then we should be good

2017-10-09 18:14 UTC, RemingtonReackhof commented on app/controllers/sessions_controller.rb
> +    # user = User.find_by(email: params[:session][:email].downcase)
Delete comments

2017-10-09 18:14 UTC, RemingtonReackhof commented on app/controllers/sessions_controller.rb
> +    # log_out if logged_in?
Delete comments, do we need the functions?

2017-10-09 18:14 UTC, RemingtonReackhof commented on config/database.yml
> +  socket: /var/run/mysqld/mysqld.sock
remove from commit

2017-10-09 18:14 UTC, RemingtonReackhof commented on test/controllers/sessions_controller_test.rb
> +  # test "the truth" do
remove comments?

2017-10-09 18:14 UTC, RemingtonReackhof commented on web-app/src/app/user.service.ts
> + //  login = function(email_, password_) {
remove comments

2017-10-09 18:14 UTC, RemingtonReackhof commented on web-app/src/app/user.ts
> +  	email:string
fix tabbing

2017-10-09 18:14 UTC, RemingtonReackhof commented on web-app/src/environments/environment.prod.ts
> +
remove newline

2017-10-09 18:14 UTC, RemingtonReackhof commented on web-app/src/environments/environment.ts
> +    // userTypes: [
remove comments

2017-10-10 22:27 UTC, lohoi commented on config/database.yml
> +  socket: /var/run/mysqld/mysqld.sock
done

2017-10-10 22:28 UTC, lohoi commented on test/controllers/sessions_controller_test.rb
> +  # test "the truth" do
done

2017-10-10 22:30 UTC, lohoi commented on web-app/src/environments/environment.prod.ts
> +
done

2017-10-10 22:31 UTC, lohoi commented on web-app/src/environments/environment.ts
> +    // userTypes: [
done

2017-10-10 22:34 UTC, merged